{
 "title": "Data Sync - {{ SYNC_APP_NAME }}",
 "tags": [ "data-sync" ],
 "time": { "from": "now/d", "to": "now" },
 "panels": [
  {
   "title": "Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Current Memory Usage",
   "type": "singlestat",
   "description": "Memory currently being used by Data Sync Server pods",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 2 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{app=\"sync-app-{{ SYNC_APP_NAME }}\"})"
    }
   ]
  },
  {
   "title": "Memory Usage In Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 2 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(process_resident_memory_bytes{app=\"sync-app-{{ SYNC_APP_NAME }}\"})",
     "legendFormat": "Average of all pods"
    },
    {
     "expr": "process_resident_memory_bytes{app=\"sync-app-{{ SYNC_APP_NAME }}\"}",
     "legendFormat": "Pod {{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Current CPU Usage",
   "type": "singlestat",
   "description": "CPU currently being used by Data Sync Server.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(process_cpu_user_seconds_total{app=\"sync-app-{{ SYNC_APP_NAME }}\"}[30s]) * 100)"
    }
   ]
  },
  {
   "title": "CPU Usage In Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_cpu_user_seconds_total{app=\"sync-app-{{ SYNC_APP_NAME }}\"}[30s]) * 100)",
     "legendFormat": "Average of all pods"
    },
    {
     "expr": "rate(process_cpu_user_seconds_total{app=\"sync-app-{{ SYNC_APP_NAME }}\"}[30s]) * 100",
     "legendFormat": "Pod {{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Queries/Mutations Resolved",
   "type": "graph",
   "description": "Number of queries and mutations resolved in time.",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(requests_resolved{operation_type=\"query\", app=\"sync-app-{{ SYNC_APP_NAME }}\"})",
     "legendFormat": "Queries"
    },
    {
     "expr": "sum(requests_resolved{operation_type=\"mutation\", app=\"sync-app-{{ SYNC_APP_NAME }}\"})",
     "legendFormat": "Mutations"
    }
   ]
  },
  {
   "title": "Resolver Timings",
   "type": "graph",
   "description": "Resolver response time in milliseconds",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(resolver_timing_ms_sum{operation_type=\"query\", app=\"sync-app-{{ SYNC_APP_NAME }}\"} / resolver_timing_ms_count{operation_type=\"query\", app=\"sync-app-{{ SYNC_APP_NAME }}\"})",
     "legendFormat": "Query"
    },
    {
     "expr": "avg(resolver_timing_ms_sum{operation_type=\"mutation\", app=\"sync-app-{{ SYNC_APP_NAME }}\"} / resolver_timing_ms_count{operation_type=\"mutation\", app=\"sync-app-{{ SYNC_APP_NAME }}\"})",
     "legendFormat": "Mutation"
    }
   ]
  },
  {
   "title": "Server response time",
   "type": "graph",
   "description": "Server response time in milliseconds",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(server_response_ms_sum{request_type=\"POST\", app=\"sync-app-{{ SYNC_APP_NAME }}\"} / server_response_ms_count{request_type=\"POST\", app=\"sync-app-{{ SYNC_APP_NAME }}\"})",
     "legendFormat": "POST"
    },
    {
     "expr": "avg(server_response_ms_sum{request_type=\"GET\", app=\"sync-app-{{ SYNC_APP_NAME }}\"} / server_response_ms_count{request_type=\"GET\", app=\"sync-app-{{ SYNC_APP_NAME }}\"})",
     "legendFormat": "GET"
    }
   ]
  },
  {
   "title": "Operations vs Conflicts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(requests_resolved{app=\"sync-app-{{ SYNC_APP_NAME }}\"})",
     "legendFormat": "Operations"
    },
    {
     "expr": "sum(conflicts{app=\"sync-app-{{ SYNC_APP_NAME }}\"})",
     "legendFormat": "Conflicts"
    }
   ]
  },
  {
   "title": "Conflicts over time per operation type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(conflicts{app=\"sync-app-{{ SYNC_APP_NAME }}\"}) by (operation_type)",
     "legendFormat": "{{operation_type}}"
    },
    {
     "expr": "sum(conflicts{app=\"sync-app-{{ SYNC_APP_NAME }}\"})",
     "legendFormat": "All Operation Types"
    }
   ]
  },
  {
   "title": "Conflicts over time per operation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(conflicts{app=\"sync-app-{{ SYNC_APP_NAME }}\"}) by (name)",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(conflicts{app=\"sync-app-{{ SYNC_APP_NAME }}\"})",
     "legendFormat": "All Operation Types"
    }
   ]
  }
 ]
}