sync_app_docker_image: "{{ SYNC_APP_DOCKER_IMAGE }}"
sync_app_docker_image_version: "{{ SYNC_APP_DOCKER_IMAGE_VERSION | default('latest', true) }}"
sync_app_metrics_endpoint: "{{ SYNC_APP_METRICS_ENDPOINT | default('', true) }}"
sync_app_graphql_endpoint: "{{ SYNC_APP_GRAPHQL_ENDPOINT | default('', true) }}"

# Sync dashboard config
dashboards_configmap: grafana-dashboards-configmap
sync_dashboard_filename: "sync-app-{{ SYNC_APP_NAME }}-dashboard.json" # name the file will have inside the config map

