sync_app_container_image: "{{ SYNC_APP_CONTAINER_IMAGE }}"
sync_app_container_image_version: "{{ SYNC_APP_CONTAINER_IMAGE_VERSION | default('latest', true) }}"
sync_app_metrics_endpoint: "{{ SYNC_APP_METRICS_ENDPOINT | default('', true) }}"
sync_app_graphql_endpoint: "{{ SYNC_APP_GRAPHQL_ENDPOINT | default('', true) }}"
db_hostname: "{{ DB_HOSTNAME | default('', true) }}"
db_port: "{{ DB_PORT | default('', true) }}"
db_username: "{{ DB_USERNAME | default('', true) }}"
db_password: "{{ DB_PASSWORD | default('', true) }}"
db_name: "{{ DB_NAME | default('', true) }}"
db_ssl: "{{ DB_SSL | default('', true) }}"

# Sync dashboard config
dashboards_configmap: grafana-dashboards-configmap
sync_dashboard_filename: "sync-app-{{ SYNC_APP_NAME }}-dashboard.json" # name the file will have inside the config map

