- name: create configmap
  k8s:
    state: present
    definition: 
      apiVersion: v1
      kind: ConfigMap
      data:
        SYNC_APP_NAME: '{{ SYNC_APP_NAME }}'
      metadata:
        name: '{{ _apb_service_instance_id }}'
        namespace: '{{ namespace }}'
        labels:
          app: sync-app-{{ SYNC_APP_NAME }}

- name: Create sync-app deployment config
  openshift_v1_deployment_config:
    name: sync-app-{{ SYNC_APP_NAME }}
    namespace: '{{ namespace }}'
    labels:
      app: sync-app-{{ SYNC_APP_NAME }}
      service: sync-app-{{ SYNC_APP_NAME }}
    replicas: 1
    selector:
      app: sync-app-{{ SYNC_APP_NAME }}
      service: sync-app-{{ SYNC_APP_NAME }}
    spec_template_metadata_labels:
      app: sync-app-{{ SYNC_APP_NAME }}
      service: sync-app-{{ SYNC_APP_NAME }}
    spec_template_metadata_annotations:
      org.aerogear.metrics/plain_endpoint: '{{ sync_app_metrics_endpoint }}'
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - "sync-app-{{ SYNC_APP_NAME }}"
        from:
          kind: ImageStreamTag
          name: "sync-app-{{ SYNC_APP_NAME }}:{{ sync_app_docker_image_version }}"
          namespace: "{{ namespace }}"
      type: ImageChange
    - type: ConfigChange
    containers:
    - name: sync-app-{{ SYNC_APP_NAME }}
      image: '{{ sync_app_docker_image }}:{{ sync_app_docker_image_version }}'
      imagePullPolicy: Always
      ports:
        - containerPort: '{{ SYNC_APP_PORT }}'
          protocol: "TCP"
      readinessProbe:
        httpGet:
          path: '/{{ sync_app_health_endpoint }}'
          port: '{{ SYNC_APP_PORT }}'
        initialDelaySeconds: 15
        timeoutSeconds: 1
      env:
      - name: DB_HOSTNAME
        value: "{{ DB_HOSTNAME }}"
      - name: DB_PORT
        value: "{{ DB_PORT|string }}"
      - name: DB_USERNAME
        value: "{{ DB_USERNAME }}"
      - name: DB_PASSWORD
        value: "{{ DB_PASSWORD }}"
      - name: DB_NAME
        value: "{{ DB_NAME }}"
      - name: DB_SSL
        value: "{{ DB_SSL }}"

- name: Create sync-app service
  k8s_v1_service:
    name: sync-app-{{ SYNC_APP_NAME }}
    namespace: '{{ namespace }}'
    labels:
      app: sync-app-{{ SYNC_APP_NAME }}
      service: sync-app-{{ SYNC_APP_NAME }}
      mobile: enabled
    selector:
      app: sync-app-{{ SYNC_APP_NAME }}
    ports:
      - name: web
        port: 443
        target_port: '{{ SYNC_APP_PORT }}'
  register: sync-app_service


- name: Create sync-app https route
  openshift_v1_route:
    annotations:
      console.alpha.openshift.io/overview-app-route: 'true'
    name: sync-app-{{ SYNC_APP_NAME }}
    namespace: '{{ namespace }}'
    labels:
      app: sync-app-{{ SYNC_APP_NAME }}
      service: sync-app-{{ SYNC_APP_NAME }}
    to_name: sync-app-{{ SYNC_APP_NAME }}
    spec_port_target_port: web
    tls_termination: edge
    tls_insecure_edge_termination_policy: Redirect
  register: sync_app_route

- name: "Create ImageStream with tag {{ sync_app_docker_image_version }} for Sync App Docker Image"
  openshift_v1_image_stream:
    name: "sync-app-{{ SYNC_APP_NAME }}"
    namespace: "{{ namespace }}"
    labels:
      app: "sync-app-{{ SYNC_APP_NAME }}"
    lookup_policy_local: False
    tags:
      - name: "{{ sync_app_docker_image_version }}"
        from:
          kind: DockerImage
          name: "{{ sync_app_docker_image }}:{{ sync_app_docker_image_version }}"
        importPolicy:
          scheduled: true

- block:
    - name: "Get service instance name by id"
      shell: oc  get -n {{ namespace }} serviceinstance -o=jsonpath='{.items[?(@.spec.externalID=="{{ _apb_service_instance_id }}")].metadata.name}'
      register: get_service_instance_out
      when: service_instance_test is undefined
  rescue:
    ####################################
    # Custom Error Message
    ####################################
    - name: Writing Termination Message '/dev/termination-log'
      shell: echo "[Creating a DC Error] - {{ ansible_failed_result.msg }}" > /dev/termination-log
    - fail: msg="[Bundle Failed! - ServiceInstance - '{{ _apb_service_instance_id | default('no _apb_service_instance_id')}}'] "

- set_fact:
    SERVICE_INSTANCE_NAME: "{{ get_service_instance_out.stdout  | default(service_instance_test) | lower }}"
  when: service_instance_test is undefined

- set_fact:
    SERVICE_INSTANCE_NAME: "{{ service_instance_test }}"
  when: service_instance_test  is defined

- block:
    - name: "Apply patch"
      shell: oc patch  -n {{ namespace }}  serviceinstance {{ SERVICE_INSTANCE_NAME }} -p '{ "metadata":{"labels":{"mdcName":"{{ SYNC_APP_NAME }}"}  }}'
      when: service_instance_test is undefined
  rescue:
    ####################################
    # Custom Error Message
    ####################################
    - name: Writing Termination Message '/dev/termination-log'
      shell: echo "[Creating a DC Error] - {{ ansible_failed_result.msg }}" > /dev/termination-log
    - fail: msg="[PATCH Failed! - Service Instance - '{{ SERVICE_INSTANCE_NAME  | default('no SERVICE_INSTANCE_NAME') }}'] "

# Check the containers in the sync-app pod and make sure they are all ready
- name: "Wait for all sync-app containers to become ready"
  shell: oc get pods --namespace={{ namespace }} --selector="deploymentconfig=sync-app-{{ SYNC_APP_NAME }}" -o jsonpath='{.items[*].status.containerStatuses[?(@.ready==true)].ready}'| wc -w
  register: aerogear_app_sync_app_result
  until: aerogear_app_sync_app_result.stdout.find("1") != -1
  retries: 30
  delay: 10

- name: "Make data available for binding"
  asb_encode_binding:
    fields:
      namespace: "{{ namespace }}"
      SYNC_APP_NAME: "{{ SYNC_APP_NAME }}"
  when: encode_asb_binding