---

# Instead of testing that the deployment config is removed, we test that the pods
# are cleaned up afterwards
- name: "Test|Check that all pods have been removed"
  shell: oc get pods --namespace={{ namespace }} --selector="deploymentconfig in (sync-app)" 2>&1
  register: result
  retries: 30
  delay: 10
  failed_when:
    - '"No resources found." not in result.stdout'
  until: '"No resources found." in result.stdout'

- name: "Test|Check that the Sync App route has been removed"
  shell: oc get route --namespace={{ namespace }} sync-app 2>&1
  register: result
  retries: 30
  delay: 10
  failed_when:
    - '"not found" not in result.stdout'
  until: '"not found" in result.stdout'

- name: "Test|Check that Sync App service has been removed"
  shell: oc get service --namespace={{ namespace }} sync-app 2>&1
  register: result
  retries: 30
  delay: 10
  failed_when:
    - '"not found" not in result.stdout'
  until: '"not found" in result.stdout'

- name: "Test|Check that all secrets have been removed"
  shell: oc get secret --namespace={{ namespace }} sync-app 2>&1
  register: result
  retries: 30
  delay: 10
  failed_when:
    - '"not found" not in result.stdout'
  until: '"not found" in result.stdout'
